name: Trigger Webhook

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened, closed]

jobs:
  send-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook data
        run: |
          curl -X POST https://your-server-domain.com/webhook \
          -H "Content-Type: application/json" \
          -H "X-GitHub-Event: ${{ github.event_name }}" \
          -d '${{ toJson(github.event) }}'
